### ISSUE TITLE
Not working with Plasma 5.26 beta

### ISSUE THREAD

**Issue by Kishore96in** [Flupp/sticky-window-snapping#23]
SUMMARY
This script no longer seems to work with kwin 5.25.90 (but it works if I downgrade kwin to 5.25.5). I have checked in a VM and using a different user account.

STEPS TO REPRODUCE
1. Upgrade to kwin 5.25.90 (beta of 5.26)
2. Install this script
3. Enable this script in System Settings > Window Management > Kwin Scripts
4. Reboot
5. Tile two windows to the left half and right half of the screen respectively, and try to resize them.

OBSERVED RESULTS
Only one of the windows is resized.
I find many error messages like this in the journalctl output:
```
kwin_x11[2964]: file:///usr/share/kwin/scripts/sticky-window-snapping/contents/code/main.js:349: Error: Cannot assign QJSValue to QRectF
```

EXPECTED RESULTS
Both windows should be resized since their borders touch

SOFTWARE VERSIONS
Operating System: Arch Linux
KDE Plasma Version: 5.25.90
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.15.68-1-lts (64-bit)
Graphics Platform: X11

ADDITIONAL INFORMATION
I have installed the script using this AUR package: https://aur.archlinux.org/packages/kwin-scripts-sticky-window-snapping-git

The script neither works on on X11 nor on Wayland.

**Comment by Flupp** [comment]
I suppose this is fixed by https://github.com/KDE/kwin/commit/0f668b05c85046fd51a41d5febc611221f4dd00a (cf. https://bugs.kde.org/show_bug.cgi?id=459369). Please reopen if this does not fix the issue.
