### ISSUE TITLE
Not working on plasma 5.22 beta

### ISSUE THREAD

**Issue by fabianski7** [Flupp/sticky-window-snapping#13]
Since I upgraded to this version of the plasma the script is no longer working.

I did a test on a virtual machine with KDE Neon unstable to check if it was a specific problem with my system but the problem also happened there.

The test was done with the version available at store.kde.org and that of github.

**Comment by mmcnutt** [comment]
Confirmed here, also not working on Fedora 34 with Plasma 5.21.90

**Comment by Flupp** [comment]
I can reproduce the problem with KWin 5.22.80 on KDE Neon unstable (`neon-unstable-20210516-0329.iso`). With `QT_LOGGING_RULES='*=true;qt.*=false' kwin --replace` I get the following console output when a window is resized:
```
file:///home/x/.local/share/kwin/scripts/sticky-window-snapping/contents/code/main.js:106: Error: Unable to determine callable overload.  Candidates are:
    clientArea(ClientAreaOption,const KWin::AbstractClient*)
    clientArea(ClientAreaOption,QPoint,int)
    clientArea(ClientAreaOption,int,int)
```
This seems to be a problem in KWin. I filed a bug report: https://bugs.kde.org/show_bug.cgi?id=437507

**Comment by zzag** [comment]
In 5.22, scripting was ported away from QtScriptEngine to QJSEngine. The latter apparently is not smart to figure out that `clientArea(ClientAreaOption,const KWin::AbstractClient*)` can be used if a non-const abstract client has been passed.

**Comment by Flupp** [comment]
[The mentioned problem in KWin](https://bugs.kde.org/show_bug.cgi?id=437507) is fixed in the release version of KWin 5.22.

Also, some additional compatibility issues are fixed in version 1.0.1 of the script.
